"""Small application-facing contracts; adapters own provider-specific details."""
from pathlib import Path
from typing import BinaryIO, Protocol


class MediaStorage(Protocol):
    def save(self, job_id: str, source: BinaryIO, max_bytes: int) -> None: ...
    def input_path(self, job_id: str) -> Path: ...
    def audio_path(self, job_id: str) -> Path: ...
    def delete(self, job_id: str) -> None: ...
    def free_bytes(self) -> int: ...
    def healthy(self) -> bool: ...
    def old_directories(self, before: float) -> list[str]: ...


class TranscriptionEngine(Protocol):
    def transcribe(self, audio: Path) -> str: ...


class MediaProcessor(Protocol):
    def normalize(self, source: Path, destination: Path) -> float: ...


class TaskDispatcher(Protocol):
    def dispatch(self, job_id: str) -> None: ...


class AdmissionControl(Protocol):
    def reserve(self, job_id: str, free_bytes: int) -> bool: ...
    def renew(self, job_id: str, seconds: int) -> bool: ...
    def release(self, job_id: str) -> None: ...
    def expired(self) -> list[str]: ...


class WorkerHeartbeat(Protocol):
    def ready(self) -> bool: ...
    def job_alive(self, job_id: str) -> bool: ...
