from typing import Protocol

class AdmissionControl(Protocol):
    def reserve(self, job_id: str, free_bytes: int) -> bool: ...
    def renew(self, job_id: str, seconds: int) -> bool: ...
    def release(self, job_id: str) -> None: ...
    def expired(self) -> list[str]: ...

class WorkerHeartbeat(Protocol):
    def ready(self) -> bool: ...
    def job_alive(self, job_id: str) -> bool: ...
