from pathlib import Path
from typing import BinaryIO, Protocol

class MediaStorage(Protocol):
    def save(self, job_id: str, source: BinaryIO, max_bytes: int) -> None: ...
    def input_path(self, job_id: str) -> Path: ...
    def audio_path(self, job_id: str) -> Path: ...
    def delete(self, job_id: str) -> None: ...
    def free_bytes(self) -> int: ...
    def healthy(self) -> bool: ...
    def old_directories(self, before: float) -> list[str]: ...
