from typing import Protocol
from transcriber.domain.job import Job

class JobRepository(Protocol):
    """Nonterminal records do not expire. Terminal TTL begins at completion.

    claim and finish MUST atomically check expected state. Duplicate delivery
    cannot re-claim a job; terminal states cannot be overwritten.
    """
    def create(self, job: Job) -> None: ...
    def get(self, job_id: str) -> Job | None: ...
    def claim(self, job_id: str) -> bool: ...
    def stage(self, job_id: str, stage: str) -> None: ...
    def complete(self, job_id: str, text: str, duration: float) -> bool: ...
    def fail(self, job_id: str, code: str, message: str, expected: str) -> bool: ...
    def active(self) -> list[Job]: ...
